### ISSUE TITLE
The exceptions occurs PSQLException

### ISSUE THREAD

**Issue by lukitk-2** [lukas-krecan/ShedLock#1117]
Hello, I'm going to try explain what my issue.
I would like to use your lib (ShedLock) but unfortunately I get exception.
My situation:
I have simple Spring boot project and I have deployed to two jboss (EAP 7.0) instance (both have different ports).
 [minimal code]

```yaml
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: xxx
        password: xxx
        driverClassName: org.postgresql.Driver
        hikari:
            maximumPoolSize: 100
            poolName: MyHikariCP
            maxLifetime: 2000000
            connectionTimeout: 15000
```

```java
@Bean
public LockProvider lockProvider(final DataSource dataSource) {
  return new JdbcTemplateLockProvider(JdbcTemplateLockProvider.Configuration.builder()
	  .withTableName("schema.shedlock")
	  .withJdbcTemplate(new JdbcTemplate(dataSource))
	  .usingDbTime()
	  .build());
}
```

```java
@Scheduled(cron = "${cron.from.config:0 0 */3 * * ?}")
@SchedulerLock(name = SHEDLOCK_TASK_NAME, lockAtMostFor = "1m")
public void myTask() {
          // e.g. here is sleep for 15sec
}
```

Seems like, It works good. Scheduler task is running only once and records in Postgre are also well. But either one instance of jboss  receive exception or other. It is almost at the same time bud intance with exception has a bit delay (very little bit).

Full stack what I could seen.

```
28.07.22 13:39:01.383|scheduling-1|ERROR|com.zaxxer.hikari.pool.HikariPool:594||trace.id=|transaction.id=|reguestId=|||MyHikariCP - Exception during pool initialization.: org.postgresql.util.PSQLException: FATAL: sorry, too many clients already
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:646) [postgresql-42.4.0.jar:42.4.0]
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:180) [postgresql-42.4.0.jar:42.4.0]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235) [postgresql-42.4.0.jar:42.4.0]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49) [postgresql-42.4.0.jar:42.4.0]
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223) [postgresql-42.4.0.jar:42.4.0]
	at org.postgresql.Driver.makeConnection(Driver.java:402) [postgresql-42.4.0.jar:42.4.0]
	at org.postgresql.Driver.connect(Driver.java:261) [postgresql-42.4.0.jar:42.4.0]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) [HikariCP-4.0.3.jar:]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) [HikariCP-4.0.3.jar:]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) [HikariCP-4.0.3.jar:]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) [HikariCP-4.0.3.jar:]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) [HikariCP-4.0.3.jar:]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) [HikariCP-4.0.3.jar:]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) [HikariCP-4.0.3.jar:]
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158) [spring-jdbc-5.2.22.RELEASE.jar:5.2.22.RELEASE]
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116) [spring-jdbc-5.2.22.RELEASE.jar:5.2.22.RELEASE]
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79) [spring-jdbc-5.2.22.RELEASE.jar:5.2.22.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:324) [spring-jdbc-5.2.22.RELEASE.jar:5.2.22.RELEASE]
	at net.javacrumbs.shedlock.provider.jdbctemplate.SqlStatementsSource.getDatabaseProductName(SqlStatementsSource.java:89) [shedlock-provider-jdbc-template-4.39.0.jar:]
	at net.javacrumbs.shedlock.provider.jdbctemplate.SqlStatementsSource.create(SqlStatementsSource.java:44) [shedlock-provider-jdbc-template-4.39.0.jar:]
	at net.javacrumbs.shedlock.provider.jdbctemplate.JdbcTemplateStorageAccessor.sqlStatementsSource(JdbcTemplateStorageAccessor.java:126) [shedlock-provider-jdbc-template-4.39.0.jar:]
	at net.javacrumbs.shedlock.provider.jdbctemplate.JdbcTemplateStorageAccessor.insertRecord(JdbcTemplateStorageAccessor.java:67) [shedlock-provider-jdbc-template-4.39.0.jar:]
	at net.javacrumbs.shedlock.support.StorageBasedLockProvider.doLock(StorageBasedLockProvider.java:81) [shedlock-core-4.39.0.jar:]
	at net.javacrumbs.shedlock.support.StorageBasedLockProvider.lock(StorageBasedLockProvider.java:65) [shedlock-core-4.39.0.jar:]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_222-4-redhat]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_222-4-redhat]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_222-4-redhat]
	at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_222-4-redhat]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) [spring-aop-5.2.22.RELEASE.jar:5.2.22.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:205) [spring-aop-5.2.22.RELEASE.jar:5.2.22.RELEASE]
	at com.sun.proxy.$Proxy126.lock(Unknown Source)
	at net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor.executeWithLock(DefaultLockingTaskExecutor.java:63) [shedlock-core-4.39.0.jar:]
	at net.javacrumbs.shedlock.spring.aop.MethodProxyScheduledLockAdvisor$LockingInterceptor.invoke(MethodProxyScheduledLockAdvisor.java:86) [shedlock-spring-4.39.0.jar:]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) [spring-aop-5.2.22.RELEASE.jar:5.2.22.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) [spring-aop-5.2.22.RELEASE.jar:5.2.22.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) [spring-aop-5.2.22.RELEASE.jar:5.2.22.RELEASE]
	at my.package.TaskCron$$EnhancerBySpringCGLIB$$4c38fcc3.myTask(<generated>) [classes:]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_222-4-redhat]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_222-4-redhat]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_222-4-redhat]
	at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_222-4-redhat]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) [spring-context-5.2.22.RELEASE.jar:5.2.22.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.22.RELEASE.jar:5.2.22.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.22.RELEASE.jar:5.2.22.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [rt.jar:1.8.0_222-4-redhat]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [rt.jar:1.8.0_222-4-redhat]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [rt.jar:1.8.0_222-4-redhat]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [rt.jar:1.8.0_222-4-redhat]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [rt.jar:1.8.0_222-4-redhat]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [rt.jar:1.8.0_222-4-redhat]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [rt.jar:1.8.0_222-4-redhat]
	at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_222-4-redhat]

28.07.22 13:39:01.399|scheduling-1|ERROR|org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95||trace.id=|transaction.id=|reguestId=|||Unexpected error occurred in scheduled task: java.lang.UnsupportedOperationException: DB time is not supported for 'Unknown'
	at net.javacrumbs.shedlock.provider.jdbctemplate.SqlStatementsSource.create(SqlStatementsSource.java:74) [shedlock-provider-jdbc-template-4.39.0.jar:]
	at net.javacrumbs.shedlock.provider.jdbctemplate.JdbcTemplateStorageAccessor.sqlStatementsSource(JdbcTemplateStorageAccessor.java:126) [shedlock-provider-jdbc-template-4.39.0.jar:]
	at net.javacrumbs.shedlock.provider.jdbctemplate.JdbcTemplateStorageAccessor.insertRecord(JdbcTemplateStorageAccessor.java:67) [shedlock-provider-jdbc-template-4.39.0.jar:]
	at net.javacrumbs.shedlock.support.StorageBasedLockProvider.doLock(StorageBasedLockProvider.java:81) [shedlock-core-4.39.0.jar:]
	at net.javacrumbs.shedlock.support.StorageBasedLockProvider.lock(StorageBasedLockProvider.java:65) [shedlock-core-4.39.0.jar:]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_222-4-redhat]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_222-4-redhat]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_222-4-redhat]
	at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_222-4-redhat]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) [spring-aop-5.2.22.RELEASE.jar:5.2.22.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:205) [spring-aop-5.2.22.RELEASE.jar:5.2.22.RELEASE]
	at com.sun.proxy.$Proxy126.lock(Unknown Source)
	at net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor.executeWithLock(DefaultLockingTaskExecutor.java:63) [shedlock-core-4.39.0.jar:]
	at net.javacrumbs.shedlock.spring.aop.MethodProxyScheduledLockAdvisor$LockingInterceptor.invoke(MethodProxyScheduledLockAdvisor.java:86) [shedlock-spring-4.39.0.jar:]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) [spring-aop-5.2.22.RELEASE.jar:5.2.22.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) [spring-aop-5.2.22.RELEASE.jar:5.2.22.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) [spring-aop-5.2.22.RELEASE.jar:5.2.22.RELEASE]
	at my.package.TaskCron$$EnhancerBySpringCGLIB$$4c38fcc3.myTask(<generated>) [classes:]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_222-4-redhat]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_222-4-redhat]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_222-4-redhat]
	at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_222-4-redhat]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) [spring-context-5.2.22.RELEASE.jar:5.2.22.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.22.RELEASE.jar:5.2.22.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.22.RELEASE.jar:5.2.22.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [rt.jar:1.8.0_222-4-redhat]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [rt.jar:1.8.0_222-4-redhat]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [rt.jar:1.8.0_222-4-redhat]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [rt.jar:1.8.0_222-4-redhat]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [rt.jar:1.8.0_222-4-redhat]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [rt.jar:1.8.0_222-4-redhat]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [rt.jar:1.8.0_222-4-redhat]
	at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_222-4-redhat]
```

If you would know to help It will make me really happy.
Thanks

**Comment by lukas-krecan** [comment]
Please Google "org.postgresql.util.PSQLException: FATAL: sorry, too many clients already"
