### ISSUE TITLE
NoSuchMethodError: redis.clients.jedis.Jedis.del(Ljava/lang/String;)J 

### ISSUE THREAD

**Issue by jsfranko** [lukas-krecan/ShedLock#1139]
**Describe the bug**

1. Which version do you use. 

    shedlock-spring 4.39.0, redis.clients.jedis 3.9.0, spring-boot 2.6.7, spring-cloud: 2021.0.2

3. Which Lock Provider:  

    shedlock-provider-redis-jedis4 4.39.0

5. ShedLock configuration

    @EnableSchedulerLock(defaultLockAtMostFor = "${lock-at-most}"), set to 2h in application.yml
    14 @Scheduled methods, @SchedulerLock(lockAtLeastFor = "${lock-at-least}", set for 30s.

7. ShedLock logs

2022-08-18 15:35:12,939 MAC8GTFL.local 10951 ERROR --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task :: **java.lang.NoSuchMethodError: redis.clients.jedis.Jedis.del(Ljava/lang/String;)J :**:: at net.javacrumbs.shedlock.provider.redis.jedis4.JedisLockProvider$JedisPoolTemplate.del(JedisLockProvider.java:157) ::: at net.javacrumbs.shedlock.provider.redis.jedis4.JedisLockProvider$RedisLock.doUnlock(JedisLockProvider.java:112) ::: at net.javacrumbs.shedlock.core.AbstractSimpleLock.unlock(AbstractSimpleLock.java:35) ::: at net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor.executeWithLock(DefaultLockingTaskExecutor.java:79) ::: at net.javacrumbs.shedlock.spring.aop.MethodProxyScheduledLockAdvisor$LockingInterceptor.invoke(MethodProxyScheduledLockAdvisor.java:86) ::: at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ::: at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ::: at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ::: at component.<SomeClass>$$EnhancerBySpringCGLIB$$c9da43be.<one of the scheduled methods>(<generated>) ::: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ::: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ::: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ::: at java.lang.reflect.Method.invoke(Method.java:498) ::: at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ::: at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ::: at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95) ::: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ::: at java.util.concurrent.FutureTask.run(FutureTask.java:266) ::: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ::: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ::: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ::: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ::: at java.lang.Thread.run(Thread.java:750) ::: 

**Expected behavior**
a long running schedule task can take up to 45 minutes in our test env.  we set the application level default lock at most for 2h's just in case behavior is different in production.  no lock at most on any scheduled method.  lock at least for 30s's on the scheduled methods.  expect long running tasks to exit without exception causing the lock to be cleared.   

**Actual behavior**
long running scheduled method ends in 45m's, throws the above exception, and leaves the locks in the database until the ttl expires (2h's).  Exception is the problem, ttl behavior is good.  tasks only run once per day.  some methods that are bit shorter are also throwing this exception.  shortest running exception don't throw this exception.

**Comment by lukas-krecan** [comment]
https://github.com/lukas-krecan/ShedLock#redis-using-jedis

**Comment by jsfranko** [comment]
I followed your link to the docs, and noted the updated version (4.41.0).  I updated my project to use that version for both shedlock-provider-redis-jedis4 and shedlock-spring.  Still getting the same error.

**Comment by lukas-krecan** [comment]
Please read the documentation carefully `shedlock-provider-redis-jedis4` does not work with jedis 3

**Comment by jsfranko** [comment]
I pulled my own dependency on redis.clients.jedis.3.9.0 and used shecklock-provider-redis-jedis4 4.41.0 and it has a transitive dependency on redis.clients.jedis.3.7.1.

**Comment by jsfranko** [comment]
I switched from jedis4 to jedis for the lock provider.  No more error.  

I guess when the time comes that we have to update to jedis 4, we'll have to override the transitive dependency on 3.7.1 jedis to a version 4 of jedis, and switch back to the jedis4 lock provider.
