### ISSUE TITLE
Issue shedlock-provider-jdbc 

### ISSUE THREAD

**Issue by ramilani12** [lukas-krecan/ShedLock#14]
Hi
I set up shedlock with spring on my batches and my environment is: Database SQL Server , Jboss EAP 6.4 and java8. I turned on logs of shedlock and I catch some errors below:

```
[2017-04-19 13:05:00,013 - DEBUG - net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor] Locked scheduledAlertaConciliacoes.
[2017-04-19 13:05:00,018 - DEBUG - net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor] Unlocked scheduledAlertaConciliacoes.
[2017-04-19 13:15:00,064 - DEBUG - net.javacrumbs.shedlock.provider.jdbc.JdbcStorageAccessor] Exception thrown when inserting record
com.microsoft.sqlserver.jdbc.SQLServerException: Violação da restrição PRIMARY KEY 'PK_shedlock'. Não é possível inserir a chave duplicada no objeto 'dbo.Spring_Batch_Locker'. O valor de chave duplicada é (scheduledAlertaConciliacoes).
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:232)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1672)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:460)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:405)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7535)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2438)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:208)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:183)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:348)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:98)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:98)
	at net.javacrumbs.shedlock.provider.jdbc.JdbcStorageAccessor.insertRecord(JdbcStorageAccessor.java:52)
	at net.javacrumbs.shedlock.support.StorageBasedLockProvider.doLock(StorageBasedLockProvider.java:70)
	at net.javacrumbs.shedlock.support.StorageBasedLockProvider.lock(StorageBasedLockProvider.java:54)
	at net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor.executeWithLock(DefaultLockingTaskExecutor.java:38)
	at net.javacrumbs.shedlock.core.DefaultLockManager.executeWithLock(DefaultLockManager.java:51)
	at net.javacrumbs.shedlock.core.LockableRunnable.run(LockableRunnable.java:35)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2017-04-19 13:15:00,072 - DEBUG - net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor] Locked scheduledAlertaConciliacoes.
[2017-04-19 13:15:00,078 - DEBUG - net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor] Unlocked scheduledAlertaConciliacoes.
```

The shedlock-provider-jdbc tries to insert on table but PK_shedlock is PK. 
I am using last version of shedock 0.9.0 both of them

**Comment by lukas-krecan-lt** [comment]
Hi, thanks for reporting. It's actually intended behavior. ShedLock is not using transactions, since it would make configuration much more complicated. It uses atomic operations instead. One of them is to try to insert new row to obtain lock. I would recommend you to use shedlock-provider-jdbc-template which can distinguish this type of exception or I can change the log from debug to trace.
