### ISSUE TITLE
Occasional Deadlock exceptions with Spring Boot 1.5.x Shedlock 1.3.0 and Mariadb

### ISSUE THREAD

**Issue by codependent** [lukas-krecan/ShedLock#147]
**Bug description**

I have a Spring Boot 1.5.x application deployed on Kubernetes with shedlock to execute a scheduled task on one of the pods (there are 2 instances of the same application running). Occasionally I'm finding a Deadlock exception caused by shedlock's lock() operation (insert statement). This usually happens after starting up a new instance, when executing the first `net.javacrumbs.shedlock.support.StorageBasedLockProvider.lock()` operation. After this everythings works fine, except that occasionally, there are additional Deadlock exceptions.

1. Versions
Spring Boot 1.5.14
Shedlock 1.3.0
Mariadb

2. Lock Provider
```
"net.javacrumbs.shedlock:shedlock-provider-jdbc-template:1.3.0",
```
3. ShedLock configuration
```
    @Scheduled(cron = "0 * * * * *")
    @SchedulerLock(name = "someTimer", lockAtMostFor = 20 * 1000, lockAtLeastFor = 10 * 1000)
    fun refreshState() {
```
4. ShedLock logs

**Expected behavior**
The scheduled task should execute in one pod without errors

**Actual behavior**
Shedlock fails throwing this exception:

```
2019-05-27T10:37:00.142 ( -  -  -  -  - ) o.s.s.s.TaskUtils$LoggingErrorHandler ERROR - Unexpected error occurred in scheduled task.
org.springframework.transaction.TransactionSystemException: Could not commit JDBC transaction; nested exception is java.sql.SQLTransactionRollbackException: (conn:1755431) Deadlock found when trying to get lock; try restarting transaction
Query is : COMMIT
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doCommit(DataSourceTransactionManager.java:316) ~[spring-jdbc-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:765) ~[spring-tx-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:734) ~[spring-tx-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:150) ~[spring-tx-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at net.javacrumbs.shedlock.provider.jdbctemplate.JdbcTemplateStorageAccessor.insertRecord(JdbcTemplateStorageAccessor.java:63) ~[shedlock-provider-jdbc-template-1.3.0.jar:na]
	at net.javacrumbs.shedlock.support.StorageBasedLockProvider.doLock(StorageBasedLockProvider.java:77) ~[shedlock-core-1.3.0.jar:na]
	at net.javacrumbs.shedlock.support.StorageBasedLockProvider.lock(StorageBasedLockProvider.java:61) ~[shedlock-core-1.3.0.jar:na]
	at net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor.executeWithLock(DefaultLockingTaskExecutor.java:38) ~[shedlock-core-1.3.0.jar:na]
	at net.javacrumbs.shedlock.core.DefaultLockManager.executeWithLock(DefaultLockManager.java:51) ~[shedlock-core-1.3.0.jar:na]
	at net.javacrumbs.shedlock.core.LockableRunnable.run(LockableRunnable.java:35) ~[shedlock-core-1.3.0.jar:na]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_161]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [na:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [na:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
Caused by: java.sql.SQLTransactionRollbackException: (conn:1755431) Deadlock found when trying to get lock; try restarting transaction
Query is : COMMIT
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:141) ~[mariadb-java-client-1.5.9.jar:na]
	at org.mariadb.jdbc.internal.util.ExceptionMapper.getException(ExceptionMapper.java:101) ~[mariadb-java-client-1.5.9.jar:na]
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwAndLogException(ExceptionMapper.java:77) ~[mariadb-java-client-1.5.9.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:226) ~[mariadb-java-client-1.5.9.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:256) ~[mariadb-java-client-1.5.9.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:302) ~[mariadb-java-client-1.5.9.jar:na]
	at org.mariadb.jdbc.MariaDbConnection.commit(MariaDbConnection.java:607) ~[mariadb-java-client-1.5.9.jar:na]
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doCommit(DataSourceTransactionManager.java:313) ~[spring-jdbc-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	... 19 common frames omitted
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Deadlock found when trying to get lock; try restarting transaction
Query is : COMMIT
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1144) ~[mariadb-java-client-1.5.9.jar:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1076) ~[mariadb-java-client-1.5.9.jar:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1031) ~[mariadb-java-client-1.5.9.jar:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:152) ~[mariadb-java-client-1.5.9.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:246) ~[mariadb-java-client-1.5.9.jar:na]
	... 22 common frames omitted
```

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. Please try to update to latest ShedLock version, it should be backward compatible and it could behave better. If not, please let me know.

**Comment by codependent** [comment]
Hi @lukas-krecan, I forgot to mention... I also tried with version 2.5.0 with the same error. Here's the stacktrace corresponding to the 2.5.0 version:

```
org.springframework.transaction.TransactionSystemException: Could not commit JDBC transaction; nested exception is java.sql.SQLTransactionRollbackException: (conn:2098487) Deadlock found when trying to get lock; try restarting transaction
Query is : COMMIT
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doCommit(DataSourceTransactionManager.java:316) ~[spring-jdbc-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:765) ~[spring-tx-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:734) ~[spring-tx-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:150) ~[spring-tx-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at net.javacrumbs.shedlock.provider.jdbctemplate.JdbcTemplateStorageAccessor.insertRecord(JdbcTemplateStorageAccessor.java:63) ~[shedlock-provider-jdbc-template-2.5.0.jar:na]
	at net.javacrumbs.shedlock.support.StorageBasedLockProvider.doLock(StorageBasedLockProvider.java:77) ~[shedlock-core-2.5.0.jar:na]
	at net.javacrumbs.shedlock.support.StorageBasedLockProvider.lock(StorageBasedLockProvider.java:61) ~[shedlock-core-2.5.0.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_161]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) ~[spring-aop-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) ~[spring-aop-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at com.sun.proxy.$Proxy93.lock(Unknown Source) ~[na:na]
	at net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor.executeWithLock(DefaultLockingTaskExecutor.java:51) ~[shedlock-core-2.5.0.jar:na]
	at net.javacrumbs.shedlock.spring.aop.MethodProxyScheduledLockAdvisor$LockingInterceptor.invoke(MethodProxyScheduledLockAdvisor.java:67) ~[shedlock-spring-2.5.0.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671) ~[spring-aop-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at es.mma.architecture.devportal.scheduling.archmonitor.ApplicationAndLibrariesStateTimer$$EnhancerBySpringCGLIB$$98824d3e.refreshState(<generated>) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_161]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_161]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [na:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [na:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
Caused by: java.sql.SQLTransactionRollbackException: (conn:2098487) Deadlock found when trying to get lock; try restarting transaction
Query is : COMMIT
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:141) ~[mariadb-java-client-1.5.9.jar:na]
	at org.mariadb.jdbc.internal.util.ExceptionMapper.getException(ExceptionMapper.java:101) ~[mariadb-java-client-1.5.9.jar:na]
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwAndLogException(ExceptionMapper.java:77) ~[mariadb-java-client-1.5.9.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:226) ~[mariadb-java-client-1.5.9.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:256) ~[mariadb-java-client-1.5.9.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:302) ~[mariadb-java-client-1.5.9.jar:na]
	at org.mariadb.jdbc.MariaDbConnection.commit(MariaDbConnection.java:607) ~[mariadb-java-client-1.5.9.jar:na]
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doCommit(DataSourceTransactionManager.java:313) ~[spring-jdbc-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	... 33 common frames omitted
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Deadlock found when trying to get lock; try restarting transaction
Query is : COMMIT
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1144) ~[mariadb-java-client-1.5.9.jar:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1076) ~[mariadb-java-client-1.5.9.jar:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1031) ~[mariadb-java-client-1.5.9.jar:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:152) ~[mariadb-java-client-1.5.9.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:246) ~[mariadb-java-client-1.5.9.jar:na]
	... 36 common frames omitted

```

**Comment by lukas-krecan** [comment]
Hi, I am afraid I will not be able to help you with this one. Locking in MySQL is bit strange. From what I am reading, it should not happen in the default setting, with the default table structure, which has only one primary key. As I do not know which DB engine do you use and how did you create the ShedLock table, I can only send you the following links

https://dev.mysql.com/doc/refman/5.7/en/innodb-deadlocks-handling.html
https://dba.stackexchange.com/questions/86878/mysql-innodb-deadlock-for-2-simple-insert-queries
http://thushw.blogspot.com/2010/11/mysql-deadlocks-with-concurrent-inserts.html

**Comment by codependent** [comment]
Well, it doesn't really make sense, I didn't customize the table creation, this is the DDL extracted from MariaDB:

```
CREATE TABLE `shedlock` (
  `name` varchar(64) NOT NULL,
  `lock_until` timestamp NULL DEFAULT NULL,
  `locked_at` timestamp NULL DEFAULT NULL,
  `locked_by` varchar(255) NOT NULL,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
 I read the resources you added, but those scenarios shouldn't apply since there are no additional indexes (?)

I'm going to retrieve the deadlock information from the database to see the exact problem.

**Comment by lukas-krecan** [comment]
Hi, that's exactly what I am wondering about. Shedlock does only the following operations.

When we do not know if the record exists (after startup)
```
INSERT INTO shedlock (name, lock_until, locked_at, locked_by) VALUES(?, ?, ?, ?)
```

and later, when we already know that the lock exists.

```
UPDATE shedlock SET lock_until = ?, locked_at = ?, locked_by = ? WHERE name = ? AND lock_until <= ?
```

Both operations in separate transaction. See this for details https://github.com/lukas-krecan/ShedLock/blob/master/providers/jdbc/shedlock-provider-jdbc-template/src/main/java/net/javacrumbs/shedlock/provider/jdbctemplate/JdbcTemplateStorageAccessor.java

I do not see how it can result in a deadlock.

**Comment by codependent** [comment]
There's something fishy with the DB, I'm closing the issue and have a look at those logs since this doesn't seem a problem related to Shedlock.

@lukas-krecan Thanks for having a look a it.
