### ISSUE TITLE
Error using MongoDB provider with latest version of Azure Cosmos DB (Mongo API)

### ISSUE THREAD

**Issue by hirowla** [lukas-krecan/ShedLock#170]
I have been using Shedlock v3.0.0 with shedlock-provider-mongo v3.0.0 against Azure Cosmos DB (Mongo API). There has been a recent upgrade in wire protocol from using Mongo 3.2 to Mongo 3.6 (i.e decent Mongo). However since the upgrade I have been getting errors.

My application is using Spring Boot 2.1.9.RELEASE.

When executing my scheduled task, I have been getting the error below frequently. Any ideas on what might be causing it?

`Unexpected error occurred in scheduled task.
com.mongodb.MongoCommandException: Command failed with error 117 (ConflictingOperationInProgress): 'Error=117, Details='' on server some-server.mongo.cosmos.azure.com:10255. The full response is { "ok" : 0.0, "errmsg" : "Error=117, Details='", "code" : 117, "codeName" : "ConflictingOperationInProgress" }
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:179)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:293)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:255)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:444)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:72)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:200)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:269)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:131)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:123)
	at com.mongodb.operation.CommandOperationHelper$4.call(CommandOperationHelper.java:452)
	at com.mongodb.operation.OperationHelper.withReleasableConnection(OperationHelper.java:424)
	at com.mongodb.operation.CommandOperationHelper.executeRetryableCommand(CommandOperationHelper.java:445)
	at com.mongodb.operation.BaseFindAndModifyOperation.execute(BaseFindAndModifyOperation.java:69)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:193)
	at com.mongodb.client.internal.MongoCollectionImpl.executeFindOneAndUpdate(MongoCollectionImpl.java:743)
	at com.mongodb.client.internal.MongoCollectionImpl.findOneAndUpdate(MongoCollectionImpl.java:723)
	at net.javacrumbs.shedlock.provider.mongo.MongoLockProvider.lock(MongoLockProvider.java:125)
	at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:205)
	at com.sun.proxy.$Proxy118.lock(Unknown Source)
	at net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor.executeWithLock(DefaultLockingTaskExecutor.java:51)
	at net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor.executeWithLock(DefaultLockingTaskExecutor.java:40)
	at net.javacrumbs.shedlock.core.DefaultLockManager.executeWithLock(DefaultLockManager.java:51)
	at net.javacrumbs.shedlock.core.LockableRunnable.run(LockableRunnable.java:35)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. I am afraid it's an issue with CosmosDB, MongoLockProvider assumes atomicity guarantees of MonogDB and it seems that CosmosDB behaves differently than expected. See [the implementation](https://github.com/lukas-krecan/ShedLock/blob/master/providers/mongo/shedlock-provider-mongo/src/main/java/net/javacrumbs/shedlock/provider/mongo/MongoLockProvider.java#L127) for more details.

There is a 3rd party LockProvider that may help you https://github.com/jesty/shedlock-provider-cosmosdb

I have no experience with CosmosDB, so I can not advise you any further,

**Comment by hirowla** [comment]
Hi, I raised this issue with Microsoft and yourself simultaneously (I didn't know where the problem was).

It turns out that the problem is with Cosmos DB and their MongoDB 3.6 implementation - they are returning the wrong error code, which is confusing ShedLock. They will be fixing it sometime this month.

**Comment by lukas-krecan** [comment]
Thanks a lot for the info.
