### ISSUE TITLE
Can not lock method returning value

### ISSUE THREAD

**Issue by pachecopaulo** [lukas-krecan/ShedLock#180]
1. Which version do you use: 4.0.1
2. Which Lock Provider: JdbcTemplate
3. ShedLock configuration: 
```
    @Scheduled(fixedDelayString = "PT5M")
    @SchedulerLock(name = "reportBugIssueTask", lockAtMostForString = "PT10M")
```
4. ShedLock logs
```
net.javacrumbs.shedlock.spring.aop.LockingNotSupportedException: Can not lock method returning value (do not know what to return if it's locked)
	at net.javacrumbs.shedlock.spring.aop.MethodProxyScheduledLockAdvisor$LockingInterceptor.invoke(MethodProxyScheduledLockAdvisor.java:66)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at jdk.internal.reflect.GeneratedMethodAccessor868.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.cloud.sleuth.instrument.async.TraceRunnable.run(TraceRunnable.java:67)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Actual behavior**
I have upgraded from `3.0.1` to `4.0.1` and after that I keep getting the above error.

**Comment by lukas-krecan** [comment]
Thanks for feedback. Version 4.0.0 switched the default intercept mode to AOP proxy which does not support return values. You can switch back to previous behavior (PROXY_SCHEDULER mode) as described here https://github.com/lukas-krecan/ShedLock#taskscheduler-proxy

**Comment by pachecopaulo** [comment]
Got it.
Thanks for the quick reply on this.
