### ISSUE TITLE
 Error creating bean with name 'lockProvider' defined 

### ISSUE THREAD

**Issue by LaelWatkins** [lukas-krecan/ShedLock#197]
**Describe the bug**
I'm unable to start my tomcat server due to a Shedlock bean creation error.   

Below are all of the details.  What do I need to do to get past this?

1. I'm currently using v 4.3.0
2. shedlock-provider-jdbc or shedlock-provider-jdbc-template. I've tried both unsuccessfully.
3. ShedLock configuration
**pom.xml dependencies:**
`<dependency>
            <groupId>net.javacrumbs.shedlock</groupId>
            <artifactId>shedlock-spring</artifactId>
            <version>4.3.0</version>
        </dependency>
        <dependency>
            <groupId>net.javacrumbs.shedlock</groupId>
            <artifactId>shedlock-provider-jdbc</artifactId>
            <version>4.3.0</version>
         </dependency>
`

**Table definition:**
 `   CREATE TABLE [dbo].[shedlock](
        [name] [varchar](64) NOT NULL,
        [lock_until] [datetime] NULL,
        [locked_at] [datetime] NULL,
        [locked_by] [varchar](255) NOT NULL,
    CONSTRAINT [pk_shedlock] PRIMARY KEY CLUSTERED 
    (
        [name] ASC
    )
)`

**Task scheduler class**
`package org.salvationarmy.oms.logic.tasks;

import net.javacrumbs.shedlock.core.LockAssert;
import net.javacrumbs.shedlock.spring.annotation.SchedulerLock;
import org.salvationarmy.ips.logic.tasks.AbstractTask;
import org.salvationarmy.oms.adhocQuery.service.AdHocQueryDatasetService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.io.IOException;
import java.util.Date;

@Component
public class UpdateAdhocDatasetTables extends AbstractTask {

    private final Logger logger = LoggerFactory.getLogger(getClass());

    @Autowired
    AdHocQueryDatasetService adHocqueryDatasetService;

    @Scheduled(cron = "0 0/3 * * * *")
    @SchedulerLock(name = "RefreshAdHocTableRunStatus",  lockAtMostFor = "9m", lockAtLeastFor = "9m")
    @Transactional
    public void executeUpdates() throws ClassNotFoundException, IOException {
        LockAssert.assertLocked();
        login();
        logger.info("Starting dataset table updates. " + new Date());

        adHocqueryDatasetService.executeDatasetUpdate();
        
        logger.info("End dataset table updates. " + new Date());
        logout();
    }
}`

**Bean configuration**
`package org.salvationarmy.sierramist.config;

import net.javacrumbs.shedlock.core.LockProvider;
import net.javacrumbs.shedlock.provider.jdbc.JdbcLockProvider;
import net.javacrumbs.shedlock.spring.annotation.EnableSchedulerLock;
import org.salvationarmy.sierramist.logic.service.implementation.AppointmentRestService;
import org.salvationarmy.sierramist.logic.service.implementation.OMSAppointmentRestService;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import javax.sql.DataSource;

@Configuration
@EnableSchedulerLock(defaultLockAtMostFor = "9m")
public class AppConfig {

    @Bean
    public AppointmentRestService appointmentRestService() {
        return new AppointmentRestService();
    }

    @Bean
    public OMSAppointmentRestService omsAppointmentRestService() {
        return new OMSAppointmentRestService();
    }

    @Bean
    public LockProvider lockProvider(DataSource dataSource) {
        return new JdbcLockProvider(dataSource, "dbo.shedlock");
    }

}
`

4. **See below**

**Expected behavior**
I'm expecting a to see a row inserted into the dbo.shedlock table.

**Actual behavior**
I get the below error when I attempt to start my tomcat server

`ERROR 58690[localhost-startStop-1] - org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:316) - Context initialization failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'lockProvider' defined in org.salvationarmy.sierramist.config.SchedLockConfiguration: Unsatisfied dependency expressed through method 'lockProvider' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'javax.sql.DataSource' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:729)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:470)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1250)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1099)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:409)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:291)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4792)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5256)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:985)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'javax.sql.DataSource' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1509)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1104)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1065)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:815)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:721)
	... 28 more
`

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. As the exception says (`No qualifying bean of type 'javax.sql.DataSource' available: expected at least 1 bean which qualifies as autowire candidate.`) you need to provide a DataSource so the LockProvider can connect to the database.
