### ISSUE TITLE
NotSuchMethodError when @SchedulerLock  is used on method without arguments

### ISSUE THREAD

**Issue by marcins89** [lukas-krecan/ShedLock#1974]
I use shedlock 5.13.0 and when i use @SchedulerLock on method with arguments I get NoSuchMethodError. I use java 21 and springboot 3.1.5

Stack trace:
`java.lang.NoSuchMethodError: 'void org.springframework.expression.spel.support.StandardEvaluationContext.applyDelegatesTo(org.springframework.expression.spel.support.StandardEvaluationContext)'
	at net.javacrumbs.shedlock.spring.aop.SpringLockConfigurationExtractor.getEvaluationContext(SpringLockConfigurationExtractor.java:153)
	at net.javacrumbs.shedlock.spring.aop.SpringLockConfigurationExtractor.parseSpEL(SpringLockConfigurationExtractor.java:139)
	at net.javacrumbs.shedlock.spring.aop.SpringLockConfigurationExtractor.getName(SpringLockConfigurationExtractor.java:130)
	at net.javacrumbs.shedlock.spring.aop.SpringLockConfigurationExtractor.getLockConfiguration(SpringLockConfigurationExtractor.java:124)
	at net.javacrumbs.shedlock.spring.aop.SpringLockConfigurationExtractor.getLockConfiguration(SpringLockConfigurationExtractor.java:115)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:237)
	at jdk.proxy2/jdk.proxy2.$Proxy117.getLockConfiguration(Unknown Source)
	at net.javacrumbs.shedlock.spring.aop.MethodProxyScheduledLockAdvisor$LockingInterceptor.invoke(MethodProxyScheduledLockAdvisor.java:77)`

With method without arguments it works fine

**Comment by lukas-krecan** [comment]
Hi, it seems you have some version mismatch. Check what version of spring-expression you have in your classpath. The method should be availbale since 6.1.1

**Comment by marcins89** [comment]
Springboot 3.1.x uses spring-expression 6.0.13, so when I updated springboot to 3.2.0 (with spring-expression 6.1.8) it works. Thanks
