### ISSUE TITLE
Duplicate Key Exception not caught in MongoLockProvider

### ISSUE THREAD

**Issue by chhauss-a** [lukas-krecan/ShedLock#2077]
**Describe the bug**
We are using a `cosmos db` in `Azure` with a `container app` that has a scheduled task every 15 minutes. Since we only want it to run on one of our two app revisions we are using ShedLock.

I found that the [MongoLockProvider](https://github.com/lukas-krecan/ShedLock/blob/983f54cca8d81e46e5de4c90c0cc761914bba948/providers/mongo/shedlock-provider-mongo/src/main/java/net/javacrumbs/shedlock/provider/mongo/MongoLockProvider.java#L112) is catching the `MongoServerException` and checks if its a duplicate key exception (E110000). But in our case the exceptions differs as it is throwing a `MongoCommandException`. This leads to a thrown exception every 15 minutes (xx:00, xx:15, xx:30, xx:45).

**Setup**
1. Which version do you use => 5.14.0
3. Which Lock Provider => MongoLockProvider
4. ShedLock configuration
```java
@Scheduled(cron = "0 */15 * * * *")
@SchedulerLock(name = "someUniqueName", lockAtMostFor = "14m", lockAtLeastFor = "14m")
```
5. ShedLock logs
```
com.mongodb.MongoCommandException: Command failed with error 11000 (DuplicateKey): 'E11000 duplicate key error collection: <our-collection>.shedLock. Failed _id or unique index constraint.' on server <our-server>. The full response is {"ok": 0.0, "errmsg": "E11000 duplicate key error collection: <our-collection>.shedLock. Failed _id or unique index constraint.", "code": 11000, "codeName": "DuplicateKey"}
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:205)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:454)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:372)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:114)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:765)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:76)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:209)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:115)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:83)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:74)
	at com.mongodb.internal.connection.DefaultServer$OperationCountTrackingConnection.command(DefaultServer.java:299)
	at com.mongodb.internal.operation.SyncOperationHelper.lambda$executeRetryableWrite$9(SyncOperationHelper.java:243)
	at com.mongodb.internal.operation.SyncOperationHelper.lambda$withSourceAndConnection$0(SyncOperationHelper.java:127)
	at com.mongodb.internal.operation.SyncOperationHelper.withSuppliedResource(SyncOperationHelper.java:152)
	at com.mongodb.internal.operation.SyncOperationHelper.lambda$withSourceAndConnection$1(SyncOperationHelper.java:126)
	at com.mongodb.internal.operation.SyncOperationHelper.withSuppliedResource(SyncOperationHelper.java:152)
	at com.mongodb.internal.operation.SyncOperationHelper.withSourceAndConnection(SyncOperationHelper.java:125)
	at com.mongodb.internal.operation.SyncOperationHelper.lambda$executeRetryableWrite$10(SyncOperationHelper.java:229)
	at com.mongodb.internal.operation.SyncOperationHelper.lambda$decorateWriteWithRetries$11(SyncOperationHelper.java:283)
	at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:67)
	at com.mongodb.internal.operation.SyncOperationHelper.executeRetryableWrite(SyncOperationHelper.java:255)
	at com.mongodb.internal.operation.BaseFindAndModifyOperation.execute(BaseFindAndModifyOperation.java:79)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:173)
	at com.mongodb.client.internal.MongoCollectionImpl.executeFindOneAndUpdate(MongoCollectionImpl.java:761)
	at com.mongodb.client.internal.MongoCollectionImpl.findOneAndUpdate(MongoCollectionImpl.java:741)
	at net.javacrumbs.shedlock.provider.mongo.MongoLockProvider.lock(MongoLockProvider.java:107)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:216)
	at jdk.proxy3/jdk.proxy3.$Proxy169.lock(Unknown Source)
	at net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor.executeWithLock(DefaultLockingTaskExecutor.java:63)
	at net.javacrumbs.shedlock.spring.aop.MethodProxyScheduledLockAdvisor$LockingInterceptor.invoke(MethodProxyScheduledLockAdvisor.java:79)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at <our-package-name>.<our-scheduling-class>$$SpringCGLIB$$0.<our-method-name>(<generated>)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124)
	at io.micrometer.observation.Observation.observe(Observation.java:499)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.lang.VirtualThread.run(Unknown Source)
```

6. Spring Boot Starter Version => 3.3.2

**Expected behavior**
I would have expected it to not throw an error when there is already a lock since that just means it could not acquire the lock.

**Actual behavior**
An exception is thrown that it could not acquire the lock.

**Current fix**
For now I have fixed the problem by overriding the lock function of the `MongoLockProvider` to catch the `MongoCommandException` and check here for a duplicate key exception too:
```java
@Bean
public LockProvider lockProvider(final MongoClient mongo) {
    return new MongoLockProvider(mongo.getDatabase(mongoDatabaseName)) {
        @Override
        public Optional<SimpleLock> lock(LockConfiguration lockConfiguration) {
            try {
                return super.lock(lockConfiguration);
            } catch (MongoCommandException e) {
                if (e.getCode() == 11000) {  // Duplicate key error
                    return Optional.empty();
                } else {
                   throw e;
                }
            }
        }
    };
}
```

**Comment by lukas-krecan** [comment]
Thanks, can you please specify what version of Mongo and Mongo driver you are using so I can reproduce it?

**Comment by chhauss-a** [comment]
We are using `spring-boot-starter-data-mongodb` which uses the same version as spring-boot-starter (v3.3.2). 
This then uses:
`mongodb-driver-sync` in version 5.0.1
`spring-data-mongodb` in version 4.3.2

In Azure we are using `Cosmos DB for MongoDB` with Server Version 3.6

**Comment by lukas-krecan** [comment]
That's strange. `MongoCommandException` [extends](https://github.com/mongodb/mongo-java-driver/blob/r5.0.1/driver-core/src/main/com/mongodb/MongoCommandException.java#L38) `MongoServerException` so it should have been cought by the catch block in the LockProvider.

**Comment by lukas-krecan** [comment]
I only see two possible epxlanation. Either you have some old/wierd version of Mongo driver, where MongoCommandException does not extend MongoServerException or, more likely, you have multiple classloaders and therfore the classes do not match. But I admit, that both cases are pretty unlikely.

**Comment by chhauss-a** [comment]
Yes you are right, `MongoCommandException` extends `MongoServerException`.
But that means if you catch the `MongoCommandException` you catch both and if you catch `MongoServerException` you catch only that one, right?

And the `MongoLockProvider` is only catching the `MongoServerException`.

**Comment by chhauss-a** [comment]
Hm you are right, I didn't notice the extension. I will dig a little deeper to see what could possibly be the cause of this. Thanks for pointing that out!

**Comment by chhauss-a** [comment]
Hey @lukas-krecan,
as far as I can tell now the exception is already catched by the MongoLockProvider. What is causing the confusion is that we are using Azure Application Insights to get our application logs, etc. into the azure cloud.
Here it seems like the catched exceptions from ShedLock are uploaded to Azure even though they are being handled.
Maybe the catch mechanism here runs after whatever is uploading them.

I guess I will open a ticket on the applicationinsights-java repo for it. Thanks for pointing in the right direction!

**Comment by lukas-krecan** [comment]
Some JDBC drivers are logging errors when they happen regardless if you handle them or not. Maybe the Mongo driver on Azure does the same.
