### ISSUE TITLE
cant' shut down gracefull

### ISSUE THREAD

**Issue by shyding** [lukas-krecan/ShedLock#210]
**Read the documentation**
Read the documentation, especially the [troubleshooting](https://github.com/lukas-krecan/ShedLock#troubleshooting) section.

**Describe the bug**
1. Which version do you use
4.5.2
2. Which Lock Provider
4.5.2
3. ShedLock configuration

	@Bean
    public LockProvider lockProvider( DataSource dataSource ){
        return new JdbcTemplateLockProvider(dataSource);
    }

	@Override
	public void configureTasks(ScheduledTaskRegistrar taskRegistrar) {
		//创建一个线程池调度器
        ThreadPoolTaskScheduler scheduler = new ThreadPoolTaskScheduler();
  //设置线程池容量
        scheduler.setPoolSize(20);
  //线程名前缀
        scheduler.setThreadNamePrefix("taskdddd-");
  //等待时常
        scheduler.setAwaitTerminationSeconds(60);
  //当调度器shutdown被调用时等待当前被调度的任务完成
        scheduler.setWaitForTasksToCompleteOnShutdown(true);
  //设置当任务被取消的同时从当前调度器移除的策略
        scheduler.setRemoveOnCancelPolicy(true);
        // 拒绝策略
        scheduler.setRejectedExecutionHandler(
                new ThreadPoolExecutor.CallerRunsPolicy()); 
        scheduler.initialize();
  //设置任务注册器的调度器
        taskRegistrar.setTaskScheduler(scheduler);
        
     
	}
	
4. ShedLock logs

20-03-28 15:57:34 13801 [taskdddd-2] ERROR
				o.s.s.s.TaskUtils$LoggingErrorHandler -95- Unexpected error occurred in scheduled task 
org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; nested exception is java.sql.SQLException: HikariDataSource HikariDataSource (DatebookHikariCP) has been closed.
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:307)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:376)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:137)
	at net.javacrumbs.shedlock.provider.jdbctemplate.JdbcTemplateStorageAccessor.unlock(JdbcTemplateStorageAccessor.java:128)
	at net.javacrumbs.shedlock.support.StorageBasedLockProvider$StorageLock.doUnlock(StorageBasedLockProvider.java:104)
	at net.javacrumbs.shedlock.core.AbstractSimpleLock.unlock(AbstractSimpleLock.java:34)
	at net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor.executeWithLock(DefaultLockingTaskExecutor.java:76)
	at net.javacrumbs.shedlock.spring.aop.MethodProxyScheduledLockAdvisor$LockingInterceptor.invoke(MethodProxyScheduledLockAdvisor.java:76)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.youibot.web.logic.schedule.TestScheduler$$EnhancerBySpringCGLIB$$494e7b92.myTask(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
**Expected behavior**

 when force app down ,errors occources
**Actual behavior**
What happened instead.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. It seems that you are shutting down the Spring application while the lock is held by a running thread. Spring framework already closed the data-source and when the thread tries to release the lock, it's can't since it can not open JDBC connection. There is not much ShedLock could do about it.

**Comment by shyding** [comment]
thanks ! I'think may the shedlock thread is not correct lead the problem ? Have you ever meet the problem?

**Comment by urgoringo** [comment]
Hi Lukáš, thank you for this awesome library. We have been happily using this in production for year. However, I'm facing similar issue with shutdown since we have our own shutdown logic that closes datasource. 

I understand that Shedlock can't itself handle all possible ways how application can be shut down. What I would like to do is tell Shedlock that it should release all locks when I know that application needs to shut down. Is there some method I could call for this purpose?

The only thing related to shut down I have been able to find is `LockableTaskScheduler.destroy` but that does not seem to do any unlocking?

**Comment by lukas-krecan** [comment]
Hi. It's quite tricky. First of all, ShedLock does not keep track of the locks it holds. It relies on try/finally block around the tasks and the lockAtMost in case of a failure. Secondly, you are asking me to release the locks while the tasks are still running. Do you really want that? It goes against the purpose of the library.

The best way would be to let Spring close the datasource after all tasks have been finished. One way you could do it is to prevent the data-source shutdown (for example by overriding `close` method on the DataSource) and then shut it down once all the threads in executor thread pool finish (again by clever implementation of a close method on TaskScheduler). Maybe there is a cleaner way, but I do not know it.

**Comment by lukas-krecan** [comment]
This [answer](https://stackoverflow.com/questions/5891032/in-a-spring-bean-is-it-possible-to-have-a-shutdown-method-which-can-use-transact/5892829#5892829) also seems to be promissing.

**Comment by lukas-krecan** [comment]
May be related https://github.com/spring-projects/spring-framework/issues/19372

**Comment by sheng-wang-i** [comment]
For any scheduled task which uses a database connection underly, nicely shutdown is not possible by manipulating the dependency between the TaskScheduler and the DataSource. 

If your scheduled task bean has datasource or any beans use datasource injected, then your bean depends on datasource bean already.  Spring will always destroy datasource before triggering the callback of cleanup of your bean.
