### ISSUE TITLE
assertLocked fails with IllegalStateException: The task is not locked.

### ISSUE THREAD

**Issue by lackovic** [lukas-krecan/ShedLock#2283]
The following code:

```java
@Scheduled(...)
@SchedulerLock(name = "scheduledTaskName")
public void scheduledTask() {
   LockAssert.assertLocked();
   // do something
}
``` 

throws the exception:

```java
java.lang.IllegalStateException: The task is not locked.
        at net.javacrumbs.shedlock.core.LockAssert.assertLocked(LockAssert.java:63) ~[shedlock-core-5.16.0.jar:na]
``` 

using Shedlock 5.16.0 with Spring Boot 3.4.0.

Either downgrading Spring Boot to 3.3.5 or upgrading Shedlock to 6.0.2 solves the issue.

How can I write an integration test to verify the `IllegalStateException` is not thrown? I tried with the following:

```java
@SpringBootTest
@RunWith(SpringRunner.class)
@EnableSchedulerLock(defaultLockAtMostFor = "PT30S")
public class MyJobIntegrationTest {

  @Autowired private MyJob myJob;

  @Test
  public void testExecute() {
    myJob.scheduledTask();
  }
}
``` 

but this always fail with the same error, regardless of the versions of Shedlock or Spring Boot used:

```java
java.lang.IllegalStateException: The task is not locked.
        at net.javacrumbs.shedlock.core.LockAssert.assertLocked(LockAssert.java:63) ~[shedlock-core-5.16.0.jar:na]
``` 

This problem was already addressed in https://github.com/lukas-krecan/ShedLock/issues/221 with version 4.7.0 but looks like the problem still happens with version 6.0.2.

**Comment by lackovic** [comment]
I did some experiments with my scheduler configuration:

```java
@Configuration
@Aspect
@EnableScheduling
@EnableSchedulerLock(interceptMode = PROXY_SCHEDULER, defaultLockAtMostFor = "2h")
class SchedulerConfig {

  @Bean
  LockProvider lockProvider(DataSource dataSource) {
    return new JdbcTemplateLockProvider(dataSource, "scheduler_lock");
  }
``` 

and I found out that changing the `interceptMode` to `PROXY_METHOD` makes both the application and the tests work without throwing the `IllegalStateException`, regardless of the versions of Shedlock or Spring Boot used.

**Comment by lukas-krecan** [comment]
Looks like this https://github.com/lukas-krecan/ShedLock/issues/225l

**Comment by lukas-krecan** [comment]
Looks like this https://github.com/lukas-krecan/ShedLock/issues/2255, I will check about the tests
