### ISSUE TITLE
Can't find a codec for class java.time.Instant - Mongo Lock Provider

### ISSUE THREAD

**Issue by deathlover** [lukas-krecan/ShedLock#247]
**Read the documentation**
Read the documentation, especially the [troubleshooting](https://github.com/lukas-krecan/ShedLock#troubleshooting) section.

**Describe the bug**
1. Which version do you use
4.9.3

2. Which Lock Provider
Mongo Lock Provider

3. ShedLock configuration
```
<dependency>
	<groupId>net.javacrumbs.shedlock</groupId>
	<artifactId>shedlock-spring</artifactId>
	<version>4.9.3</version>
</dependency>

<dependency>
	<groupId>net.javacrumbs.shedlock</groupId>
	<artifactId>shedlock-provider-mongo</artifactId>
	<version>4.9.3</version>
</dependency>
```

Main File (with main function):
`@EnableSchedulerLock(defaultLockAtMostFor = "PT30S")
`

Config File:
```
@Configuration
public class SchedulerConfiguration {
    @Bean
    public LockProvider lockProvider(MongoClient mongo) {
        return new MongoLockProvider(mongo.getDatabase("shedlock"));
    }
}
```

Sheduler File:
```
@Scheduled(fixedRate = 50000)
@SchedulerLock(name = "poll")
public void poll() {
	
}
```

4. ShedLock logs
```
org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class java.time.Instant.
        at org.bson.codecs.configuration.CodecCache.getOrThrow(CodecCache.java:46)
        at org.bson.codecs.configuration.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:63)
        at org.bson.codecs.configuration.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:37)
        at com.mongodb.client.model.BuildersHelper.encodeValue(BuildersHelper.java:35)
        at com.mongodb.client.model.Updates$SimpleUpdate.toBsonDocument(Updates.java:442)
        at com.mongodb.client.model.Updates$CompositeUpdate.toBsonDocument(Updates.java:605)
        at com.mongodb.MongoCollectionImpl.toBsonDocument(MongoCollectionImpl.java:1074)
        at com.mongodb.MongoCollectionImpl.executeFindOneAndUpdate(MongoCollectionImpl.java:766)
        at com.mongodb.MongoCollectionImpl.findOneAndUpdate(MongoCollectionImpl.java:748)
        at net.javacrumbs.shedlock.provider.mongo.MongoLockProvider.lock(MongoLockProvider.java:143)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:206)
        at com.sun.proxy.$Proxy151.lock(Unknown Source)
        at net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor.executeWithLock(DefaultLockingTaskExecutor.java:63)
        at net.javacrumbs.shedlock.spring.aop.MethodProxyScheduledLockAdvisor$LockingInterceptor.invoke(MethodProxyScheduledLockAdvisor.java:85)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
        at co.quickwork.automation.workflow.service.PollService$$EnhancerBySpringCGLIB$$df2f271d.poll(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Expected behavior**
Database and collection should have get created

**Actual behavior**
Above error appears

**Comment by lukas-krecan** [comment]
Please try to upgrade Mongo client library

**Comment by deathlover** [comment]
Mongo driver is at version 3.11 - up to date
Mongo Client - spring-boot-starter-data-mongodb (latest)

**Comment by lukas-krecan** [comment]
Please check again mongo-java-driver version. For example MongoCollectionImpl:748 in 3.11.0 is an empty line so the stack trace is apparently from some other version.

**Comment by deathlover** [comment]
Sorry, my bad
Mongo driver Version is 3.6.4
It matches the minimum requirement, or should i upgrade

**Comment by lukas-krecan** [comment]
Please upgrade, I will update README
