### ISSUE TITLE
Tomcat Issues

### ISSUE THREAD

**Issue by ramilani12** [lukas-krecan/ShedLock#3]
Is shedlock compatible with tomcat?
I´ve been trying to run on tomcat but I got some errors below:

I used 

```
<dependency>
    		<groupId>net.javacrumbs.shedlock</groupId>
    		<artifactId>shedlock-spring</artifactId>
    		<version>0.5.0</version>
		</dependency>
```

```
<dependency>
    		<groupId>net.javacrumbs.shedlock</groupId>
    		<artifactId>shedlock-provider-jdbc-template</artifactId>
    		<version>0.5.0</version>
		</dependency>
```

```
GRAVE: A child container failed during start
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/BS-CONCILIA-PORTAL]]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:915)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:871)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1407)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1397)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/BS-CONCILIA-PORTAL]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:153)
	... 6 more
Caused by: org.apache.catalina.LifecycleException: Failed to start component [org.apache.catalina.webresources.StandardRoot@7795bcd1]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:153)
	at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4929)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5059)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	... 6 more
Caused by: org.apache.catalina.LifecycleException: Failed to initialize component [org.apache.catalina.webresources.JarResourceSet@3eab89d9]
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:106)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:136)
	at org.apache.catalina.webresources.StandardRoot.startInternal(StandardRoot.java:699)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	... 9 more
Caused by: java.lang.IllegalArgumentException: java.util.zip.ZipException: invalid LOC header (bad signature)
	at org.apache.catalina.webresources.JarResourceSet.initInternal(JarResourceSet.java:139)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:102)
	... 12 more
Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
	at java.util.zip.ZipFile.read(Native Method)
	at java.util.zip.ZipFile.access$1400(ZipFile.java:60)
	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:717)
	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:419)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at sun.misc.IOUtils.readFully(IOUtils.java:65)
	at java.util.jar.JarFile.getBytes(JarFile.java:425)
	at java.util.jar.JarFile.getManifestFromReference(JarFile.java:193)
	at java.util.jar.JarFile.getManifest(JarFile.java:180)
	at org.apache.catalina.webresources.JarResourceSet.initInternal(JarResourceSet.java:137)
	... 13 more
```

**Comment by lukas-krecan** [comment]
Seems to be corrupt jar file as as described here ⁣​http://stackoverflow.com/questions/14495040/tomcat-server-fails-to-start-the-server-and-application-in-sts

26. 1. 2017 19:08, 19:08, Raphael Milani <notifications@github.com> napsal/a:

**Comment by ramilani12** [comment]
Hi
Lucas

Nice work your library, but there is an issue with shedlock-provider-jdbc-template maybe the jar is corrupt. I change to shedlock-provider-jdbc and now is working properly. 
On my local development I use Tomcat 8 and Java 8 with SqlServer 2014 another enviroment with Jboss clustered with two nodes and database sqlserver 204 is working properly as well.

I needed to create table directly on database that is script for SqlServer with want to add the rep:

```
CREATE TABLE [dbo].[shedlock](
	[name] [varchar](64) NOT NULL,
	[lock_until] [datetime] NULL,
	[locked_at] [datetime] NULL,
	[locked_by] [varchar](255) NOT NULL,
 CONSTRAINT [PK_shedlock] PRIMARY KEY CLUSTERED 
(
	[name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
```

**Comment by Harshit-Shrivastava** [comment]
Hi Lucas,

What is `[locked_by] [varchar](255) NOT NULL` field in the table? Is it possible to set this to an `instance name` or `node name` from the application, or make it a composite key (alongside `[name] [varchar](64) NOT NULL` field)?

I guess I am exploring to see the option where 2-3 tasks are using ShedLock (different lock name for each task) in a 4+ node environment and making sure that not all tasks are running on the same node (CPU/memory/load consideration)

**Comment by dogbekekeli21** [comment]
CREATE TABLE [dbo].[shedlock](
	[name] [varchar](64) NOT NULL,
	[lock_until] [datetime] NULL,
	[locked_at] [datetime] NULL,
	[locked_by] [varchar](255) NOT NULL,
 CONSTRAINT [PK_shedlock] PRIMARY KEY CLUSTERED 
(
	[name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
