### ISSUE TITLE
Unable to configure Shedlock with Redis

### ISSUE THREAD

**Issue by abhishekjoy1** [lukas-krecan/ShedLock#327]
**Is your feature request related to a problem? Please describe.**
I am getting following error while I am configuring Spring scheduler with Shedlock backed by Redis:

```
ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task
java.lang.NoClassDefFoundError: net/javacrumbs/shedlock/core/ClockProvider
	at net.javacrumbs.shedlock.provider.redis.spring.RedisLockProvider.getMsUntil(RedisLockProvider.java:111)
	at net.javacrumbs.shedlock.provider.redis.spring.RedisLockProvider.getExpiration(RedisLockProvider.java:107)
	at net.javacrumbs.shedlock.provider.redis.spring.RedisLockProvider.lock(RedisLockProvider.java:98)
	at jdk.internal.reflect.GeneratedMethodAccessor176.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:205)
	at com.sun.proxy.$Proxy117.lock(Unknown Source)
	at net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor.executeWithLock(DefaultLockingTaskExecutor.java:54)
	at net.javacrumbs.shedlock.spring.aop.MethodProxyScheduledLockAdvisor$LockingInterceptor.invoke(MethodProxyScheduledLockAdvisor.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at com.salesforce.tm.scheduler.GusAPIScheduler$$EnhancerBySpringCGLIB$$29a9d6db.gusAPICronJob(<generated>)
	at jdk.internal.reflect.GeneratedMethodAccessor175.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I have followed the steps exactly as mentioned in the documentation. I am unable to fix this issue. 

**Describe the solution you'd like**
I think one small example of Spring scheduler application with Shedlock backed by Redis would help. I can get an idea regarding what I am missing.

**Describe alternatives you've considered**
As I have not been able to configure Shedlock with Redis, so I have taken MySQL approach.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. Please, check that all ShedLock modules have the same version.

**Comment by abhishekjoy1** [comment]
Sure @lukas-krecan,  I will try as you mentioned and update here.

**Comment by abhishekjoy1** [comment]
Hi, @lukas-krecan I have been able to resolve the issue. Now I am running Shedlock with Redis. One question, I am seeing with Redis, following entry is getting dynamically created in Redis:

      >keys *
      >"job-lock:default:gusSyncSAData"
      >get job-lock:default:gusSyncSAData
      >"ADDED:2020-08-17T08:36:13.456Z@amalik1-ltm.internal.salesforce.com"
     
Unlike MySQL here there is no value is maintained for `locked_until`. 

So, I assume it runs with below logic:

Once a POD acquires the lock, one entry like above gets created in Redis, which gets deleted after `Min(lock_at_least_duration, time_to_run_job)`

So during this time, none of any other PODs will be able to acquire the lock.

Also, it has a key advantage over MySQL i.e. it has no extra operational overhead like MySQL. We have to just add the dependency and add the lock provider configuration in the application. 

Please correct me, if I am wrong.

**Comment by lukas-krecan** [comment]
Please see the implementation https://github.com/lukas-krecan/ShedLock/blob/master/providers/redis/shedlock-provider-redis-spring/src/main/java/net/javacrumbs/shedlock/provider/redis/spring/RedisLockProvider.java
