### ISSUE TITLE
Error using hazelcast lock provider

### ISSUE THREAD

**Issue by tonivade** [lukas-krecan/ShedLock#33]
Hi!

We are trying to use hazelcast provider connecting to a **remote cluster** (not an embedded hazelcast instance), but we have an error:

```
2017-09-06 07:22:12.705 ERROR 8 --- [WATCHDOG_THREAD] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.

java.lang.UnsupportedOperationException: Client has no local member!
        at com.hazelcast.client.proxy.ClientClusterProxy.getLocalMember(ClientClusterProxy.java:61)
        at net.javacrumbs.shedlock.provider.hazelcast.HazelcastLockProvider.getLocalMemberUuid(HazelcastLockProvider.java:144)
        at net.javacrumbs.shedlock.provider.hazelcast.HazelcastLockProvider.addNewLock(HazelcastLockProvider.java:127)
        at net.javacrumbs.shedlock.provider.hazelcast.HazelcastLockProvider.tryLock(HazelcastLockProvider.java:94)
        at net.javacrumbs.shedlock.provider.hazelcast.HazelcastLockProvider.lock(HazelcastLockProvider.java:79)
        at net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor.executeWithLock(DefaultLockingTaskExecutor.java:38)
        at net.javacrumbs.shedlock.core.DefaultLockManager.executeWithLock(DefaultLockManager.java:51)
        at net.javacrumbs.shedlock.core.LockableRunnable.run(LockableRunnable.java:35)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

When we try against an embedded hazelcast, it works like a charm.

Thanks!

**Comment by lukas-krecan-lt** [comment]
@peyo Any ideas?

**Comment by lukas-krecan** [comment]
Released as 0.15.1

**Comment by tonivade** [comment]
Thanks a lot @lukas-krecan 

Tomorrow I'll test this again

**Comment by peyo** [comment]
@lukas-krecan I just saw this issue, sorry.

Indeed, I never use HazelcastClient on my projects so I not test this use case. 

The solution you have pushed is the best and now the hazelcast-provider have the same behavior as others : when a member of cluster shutdown there locks are kept until "AtMostUntil".

Thanks for your PR

**Comment by lukas-krecan** [comment]
@peyo Thanks, I was not sure about it.

**Comment by tonivade** [comment]
I have tested it again, and it works perfectly.

Thanks!
