### ISSUE TITLE
SchedLock multiple schedules running in kubernetes clustered environment

### ISSUE THREAD

**Issue by jedgard81** [lukas-krecan/ShedLock#337]
I am using schedLock to lock the execution of a method in a cluster environment. This worked well until I added another method using schedLock with a different name, it creates the lock but then schedLock makes the scheduler fail and never executes.

There are the methods:

```
  @Scheduled(cron = "0 0 2 * * ?", zone = "America/New_York")
  @SchedulerLock(name = "reportCarSchedule",
          lockAtMostForString = "PT6H",
          lockAtLeastForString = "PT5M")
  public void reportScheduledJob() { 
  }
```

```
  @Scheduled(cron = "0 0 4 * * ?", zone = 
    "America/New_York")
  @SchedulerLock(name = "reportTripSchedule",
      lockAtMostForString = "PT6H",
      lockAtLeastForString = "PT5M")
  public void reportTripJob() {
  }
```
Then I am getting this error anytime the second one tries at 4 am, which is the new one. The first one runs at 2 AM fine without issues.

```
Unexpected error occurred in scheduled task.
com.mongodb.MongoSocketReadException: Prematurely reached end of stream
    at com.mongodb.connection.SocketStream.read(SocketStream.java:88)
    at com.mongodb.connection.InternalStreamConnection.receiveResponseBuffers(InternalStreamConnection.java:494)
    at com.mongodb.connection.InternalStreamConnection.receiveMessage(InternalStreamConnection.java:224)
    at com.mongodb.connection.UsageTrackingInternalConnection.receiveMessage(UsageTrackingInternalConnection.java:96)
    at com.mongodb.connection.DefaultConnectionPool$PooledConnection.receiveMessage(DefaultConnectionPool.java:440)
    at com.mongodb.connection.CommandProtocol.execute(CommandProtocol.java:112)
    at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:168)
    at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:289)
    at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:176)
    at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:216)
    at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:153)
    at com.mongodb.operation.FindAndUpdateOperation$1.call(FindAndUpdateOperation.java:335)
    at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:426)
    at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:417)
    at com.mongodb.operation.FindAndUpdateOperation.execute(FindAndUpdateOperation.java:331)
    at com.mongodb.Mongo.execute(Mongo.java:845)
    at com.mongodb.Mongo$2.execute(Mongo.java:828)
    at com.mongodb.MongoCollectionImpl.findOneAndUpdate(MongoCollectionImpl.java:435)
    at net.javacrumbs.shedlock.provider.mongo.MongoLockProvider.lock(MongoLockProvider.java:123)
    at net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor.executeWithLock(DefaultLockingTaskExecutor.java:50)
    at net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor.executeWithLock(DefaultLockingTaskExecutor.java:39)
    at net.javacrumbs.shedlock.core.DefaultLockManager.executeWithLock(DefaultLockManager.java:51)
    at net.javacrumbs.shedlock.core.LockableRunnable.run(LockableRunnable.java:35)
    at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
    at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)

```

Any help would be appreciated

SchedLock 2.1.0

**Comment by lukas-krecan** [comment]
Hi, from the stack trace it seems that connection to Mongo is not working as expected. I would recommend to update to newest ShedLock version.

**Comment by jedgard81** [comment]
I may not be able to go all the way to the newest , this spring framework is only 1.2.7 it seems. Which version do you recommend for a 1.2.7 spring version?.  Thanks
