### ISSUE TITLE
Shedlock should skip in case of reactive scheduler lock but it throws null pointer exception.

### ISSUE THREAD

**Issue by subhransu-sahu-by** [lukas-krecan/ShedLock#353]
**Read the documentation**
Read the documentation, especially the [troubleshooting](https://github.com/lukas-krecan/ShedLock#troubleshooting) section.

Update to the latest version.

**Describe the bug**
1. Which version do you use - 4.14.0
2. Which Lock Provider - ReactiveStreamsMongoLockProvider
3. ShedLock configuration - 

```
@SchedulerLock(name = "getPayment", lockAtMostForString = "14m",lockAtLeastForString = "10m")
    public Mono<Boolean> validateOrder(OrderWrapperDetailRequest orderWrapperDetailRequest) {
        return createOrderRepresentationValidator.validate(orderWrapperDetailRequestAndOrderRepresentationMapper.toOrderRepresentation(orderWrapperDetailRequest),
                customValidationConfigurationsCacheService.getAll(orderWrapperDetailRequest.getOrgId()));
    }
4. ShedLock logs-

java.lang.NullPointerException: null
	at com.blueyonder.om.order.services.api.controller.OrderValidationController.validateOrderWrapperDetailRequest(OrderValidationController.java:50) ~[order-services-api-1.0-SNAPSHOT.jar!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.web.reactive.result.method.InvocableHandlerMethod.lambda$invoke$0(InvocableHandlerMethod.java:147) ~[spring-webflux-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118) [reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1712) [reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.MonoZip$ZipCoordinator.signal(MonoZip.java:247) [reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.MonoZip$ZipInner.onNext(MonoZip.java:329) [reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:173) [reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:92) [reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192) [reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67) [reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73) [reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1712) [reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144) [reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:103) [reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:287) [reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:330) [reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1712) [reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:160) [reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136) [reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252) [reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136) [reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.netty.channel.FluxReceive.terminateReceiver(FluxReceive.java:421) [reactor-netty-0.9.6.RELEASE.jar!/:0.9.6.RELEASE]
	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:211) [reactor-netty-0.9.6.RELEASE.jar!/:0.9.6.RELEASE]
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:369) [reactor-netty-0.9.6.RELEASE.jar!/:0.9.6.RELEASE]
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:367) [reactor-netty-0.9.6.RELEASE.jar!/:0.9.6.RELEASE]
	at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:489) [reactor-netty-0.9.6.RELEASE.jar!/:0.9.6.RELEASE]
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:90) [reactor-netty-0.9.6.RELEASE.jar!/:0.9.6.RELEASE]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
	at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:214) [reactor-netty-0.9.6.RELEASE.jar!/:0.9.6.RELEASE]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321) [netty-codec-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295) [netty-codec-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.48.Final.jar!/:4.1.48.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.48.Final.jar!/:4.1.48.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Expected behavior**

It should skip execution or should hold the execution.

**Actual behavior**
Throwing NPE

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. If the lock can not be obtained, ShedLock returns null which seems to be the cause. Out of curiosity, what would you expect to be returned in such case?

**Comment by subhransu-sahu-by** [comment]
Some customException like lock cannot be obtained or should wait till lock times out something like that.
