### ISSUE TITLE
Spring devtools and Java 11 compatiblity?

### ISSUE THREAD

**Issue by ajainy** [lukas-krecan/ShedLock#368]
Hi, I am running on SB 2.3.x + Java 11 stack. 
I downloaded latest jar of shedlock but I am not able to run, while devtools are in dependency path. 

**Work Around**
It worked when I removed devtools dependency. 

**Describe the bug**
1. Which version do you use   -> 4.19.0
2. Which Lock Provider -> JDBC 
3. ShedLock configuration -> ? Annotation based. (as documented in README)
4. ShedLock logs -> Nothing in logs, even I did DEBUG level (as mentioned)

**Expected behavior**
System comes up.

**Actual behavior**
-=-=-=-=
Caused by: java.lang.IllegalAccessError: class net.javacrumbs.shedlock.spring.aop.SpringLockConfigurationExtractor$$EnhancerBySpringCGLIB$$46ec4606 cannot access its superclass net.javacrumbs.shedlock.spring.aop.SpringLockConfigurationExtractor (net.javacrumbs.shedlock.spring.aop.SpringLockConfigurationExtractor$$EnhancerBySpringCGLIB$$46ec4606 is in unnamed module of loader org.springframework.boot.devtools.restart.classloader.RestartClassLoader @ec5b7e4; net.javacrumbs.shedlock.spring.aop.SpringLockConfigurationExtractor is in unnamed module of loader 'app')
        at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[na:na]
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:535) ~[spring-core-5.2.9.RELEASE.jar:5.2.9.RELEASE]
=-=-=

**Comment by M-Thirumal** [comment]
Same with 2.4.X

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. it looks similar to this https://github.com/spring-projects/spring-boot/issues/7267#issuecomment-310147172

**Comment by zeljko-mirovic** [comment]
I think this is solution: #367

**Comment by ajainy** [comment]
It worked for me. I added file spring-devtools.properties in META-INF folder
and I added this line  `restart.include.shedlock=/shedlock-.+\.jar`

Somehow I was playing with exclude pattern. But it has to be include.

**Comment by lukas-krecan** [comment]
Should be fixed in 4.19.1
