### ISSUE TITLE
Shedlock fails on H2 database

### ISSUE THREAD

**Issue by rgala** [lukas-krecan/ShedLock#380]
Trying to use Shedlock on H2 database, but it fails with the following error:

```
Column "MICROSECOND" not found; SQL statement:
UPDATE shedlock SET lock_until = TIMESTAMPADD(MICROSECOND, ?, CURRENT_TIMESTAMP(3)), locked_at = CURRENT_TIMESTAMP(3), locked_by = ? WHERE name = ? AND lock_until <= CURRENT_TIMESTAMP(3) [42122-191]
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
    at org.h2.message.DbException.get(DbException.java:179)
    at org.h2.message.DbException.get(DbException.java:155)
    at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
    at org.h2.expression.Function.optimize(Function.java:2245)
    at org.h2.command.dml.Update.prepare(Update.java:192)
    at org.h2.command.Parser.prepareCommand(Parser.java:257)
    at org.h2.engine.Session.prepareLocal(Session.java:560)
    at org.h2.engine.Session.prepareCommand(Session.java:501)
    at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
    at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
    at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:276)
    at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:337)
    at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
    at org.springframework.jdbc.core.PreparedStatementCreatorFactory$PreparedStatementCreatorImpl.createPreparedStatement(PreparedStatementCreatorFactory.java:237)
    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:615)
    ... 35 common frames omitted
```

Using H2 driver 1.4.191 and Shedlock 4.14.0. Spring data source is configured as below:

```
    @Bean
    public DataSource dataSource() throws SQLException {
        HikariDataSource dataSource = new HikariDataSource();
        dataSource.setDriverClassName(org.h2.Driver.class.getName());
        dataSource.setJdbcUrl("jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE");
        dataSource.setUsername("sa");
        dataSource.setPassword("");
        return dataSource;
    }
```

Shedlock configuration:

```
    @Bean
    public LockProvider lockProvider(DataSource dataSource) {
        return new JdbcTemplateLockProvider(
                JdbcTemplateLockProvider.Configuration.builder()
                        .withJdbcTemplate(new JdbcTemplate(dataSource))
                        .usingDbTime()
                        .build()
        );
    }
```

**Comment by lukas-krecan** [comment]
Shoud work with H2 version 1.4.200? If it does not, feel free to reopen this ticket.

**Comment by rgala** [comment]
Does not work on 1.4.200 either.

**Comment by lukas-krecan** [comment]
Please double check that you really are on 1.4.200. I have a [test](https://github.com/lukas-krecan/ShedLock/blob/master/providers/jdbc/shedlock-provider-jdbc-template/src/test/java/net/javacrumbs/shedlock/provider/jdbctemplate/H2JdbcTemplateLockProviderIntegrationTest.java) that failed on 1.4.191 as you described but is passing on 1.4.200.

**Comment by rgala** [comment]
You were right. Indeed it works on 1.4.200. I changed version in my Gradle project but it still used 1.4.191 for some reason. Sorry for bothering :)
