### ISSUE TITLE
relation "shedlock" does not exist

### ISSUE THREAD

**Issue by MSaifAsif** [lukas-krecan/ShedLock#458]
**Describe the bug**
1. Which version do you use `4.21.0`
2. Which Lock Provider `JdbcTemplateLockProvider`
3. ShedLock configuration 
```java
    @Bean
    public LockProvider lockProvider(DataSource dataSource) {
        return new JdbcTemplateLockProvider(
                JdbcTemplateLockProvider.Configuration.builder()
                        .withJdbcTemplate(new JdbcTemplate(dataSource))
                        .withTableName("shedlock")
                        .usingDbTime()
                        .build()
        );
```

4. ShedLock logs
```bash
Caused by: org.postgresql.util.PSQLException: ERROR: relation "shedlock" does not exist
  Position: 8
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:130)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.springframework.jdbc.core.JdbcTemplate.lambda$update$0(JdbcTemplate.java:867)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617)
	... 34 common frames omitted

```

**Expected behavior**
Shedlock finds the table and acquires lock

**Actual behavior**
Throws exception about table not found

**Comment by lukas-krecan** [comment]
Hi, can you please describe what did you do to debug it yourself?

**Comment by MSaifAsif** [comment]
So I tried passing in my own custom implementation of `datasource` Bean and doing so while debugging I noticed that the bean is created fine but the `jdbcTemplate` is connected to a database called `default` (no idea yet where this is coming from)

**Comment by lukas-krecan** [comment]
Hi, it seems that you data-source is misconfigured. In postgress it's quite tricky to get it right, I would recommned you to play with the JDBC connection String. If everything fails and it's an issue with different schema, you can specify the table name in LockProvider config in form 'schema.shedlock'.

As it is an issue with your configuration I will close this ticket. Good luck.
