### ISSUE TITLE
The task is not locked

### ISSUE THREAD

**Issue by kieutuan218** [lukas-krecan/ShedLock#616]
I made the config as follows but shedlock doesn't work when I deploy to aws. It works in localhost
I've checked the logs. It shows: The task is not locked
I don't see log: Already locked, Not executing, or anything else logs about shedlock
*Note: I have another scheduler service that use shedlock. It's working. But this schedule not work. I don't know why

ShedLock version: 4.24.0
Spring version: 2.1.2

Source code:
```
private static final long INITIAL_DELAY = 1 * 60 * 1000L; // 1 minutes

private static final long FIXED_RATE = 1 * 60 * 1000L; // 1 minutes

private static final String NAME_OF_SERVICE = "NotificationSchedule";

private static final String TIME_LOCK = "50s";

@Scheduled(initialDelay = INITIAL_DELAY, fixedRate = FIXED_RATE)
@SchedulerLock(name = NAME_OF_SERVICE, lockAtMostFor = TIME_LOCK, lockAtLeastFor = TIME_LOCK)
public void start() {
    // To assert that the lock is held (prevents misconfiguration errors)
    LockAssert.assertLocked();

    // Do something
}
```

Logs:
```
IllegalStateException: The task is not locked.
java.lang.IllegalStateException: The task is not locked.
	at net.javacrumbs.shedlock.core.LockAssert.assertLocked(LockAssert.java:47)
	at sg.com.carclub.carclubbackend.schedule.BatchNotificationSchedule.start(BatchNotificationSchedule.java:326)
	at sun.reflect.GeneratedMethodAccessor290.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by lukas-krecan** [comment]
There is not much I can help you with.

**Comment by kieutuan218** [comment]
I changed SchedulerLock name to "NotificationSchedule1" and it's working now.
I guess a thread that has blocked this task forever. Do you know how to stop/clear it ?

**Comment by lukas-krecan** [comment]
Please, read the documentation

**Comment by kieutuan218** [comment]
The document says: ver 0.18.2 ablility to clean lock cache
But I don't see the sample code. I tried method lockProvider.clearCache() but I still not work.

One more problem. Although I've deleted the key "NotificationSchedule" from the database and restart the server. But still error: The task is not locked. Key "NotificationSchedule" not insert to database
Do you have anything to suggest for me to find the root cause of this problem?
