### ISSUE TITLE
Is it possible add a global @SingleUse for spring boot application?

### ISSUE THREAD

**Issue by zhengfc** [lukas-krecan/ShedLock#73]
Hope add global definition for spring-boot application. For example, if I add annotation at spring boot launch class, will guard all task execute once in nodes:  
```
@SpringBootAppliction  
@EnableScheduling  
@SingleUse  
```

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback and sorry for the delay. If I understand you correctly, you want to add one annotation which would automatically put lock on all scheduled tasks?  It is quite easy to implement but I am afraid that it's a bit dangerous. We need a name for each lock and the only way to generated it automatically is to use method signature - ClassName.methodName(). In my opinion it's quite fragile since you can rename the class or the method and when you deploy the change only to part of the cluster, the task will be executed twice. That's why I hesitate to add it.

**Comment by wankang189** [comment]
17:42:19.732 1796972 [ThreadPoolTaskScheduler-1] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
net.javacrumbs.shedlock.support.LockException: Can not remove node
	at net.javacrumbs.shedlock.provider.redis.spring.RedisLockProvider$RedisLock.unlock(RedisLockProvider.java:107)
	at net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor.executeWithLock(DefaultLockingTaskExecutor.java:44)
	at net.javacrumbs.shedlock.core.DefaultLockManager.executeWithLock(DefaultLockManager.java:51)
	at net.javacrumbs.shedlock.core.LockableRunnable.run(LockableRunnable.java:35)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Address already in use (connect failed)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:286)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.getConnection(JedisConnectionFactory.java:469)
	at net.javacrumbs.shedlock.provider.redis.spring.RedisLockProvider$RedisLock.unlock(RedisLockProvider.java:104)
	... 11 common frames omitted
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Address already in use (connect failed)
	at redis.clients.jedis.Connection.connect(Connection.java:207)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:93)
	at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1767)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:281)
	... 13 common frames omitted
Caused by: java.net.ConnectException: Address already in use (connect failed)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:400)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:243)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:225)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:402)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at redis.clients.jedis.Connection.connect(Connection.java:184)
	... 16 common frames omitted

**Comment by zhengfc** [comment]
Hi, thanks for you reply. As you said, you use a method name as lock signature.  Some time we deploy for change part of the cluster in AB test, I think job or task as AB test in application is not suitable. So, if you check some method have specific annotation you automatically disable global annotation. Of course, it's just my opinion.

**Comment by ivaylo5ev** [comment]
Or maybe just provide the lock name in the annotation? Of course, users would need to know what to worry about, but IMHO an annotation parameter is more likely to survive than a method signature name.

**Comment by zHaytam** [comment]
@ivaylo5ev This would mean only one task would run, which isn't the desired behavior no?
@zhengfc Maybe as a fallback, check if the class has a `Component` annotation and a `name` set? That should be unique enough.

**Comment by ivaylo5ev** [comment]
@zHaytam , yes it would and this is NOT the desired behaviour indeed. I have misread / misunderstood the initial request, so ignore my comment above.
