### ISSUE TITLE
Shedlock not working with jedis 4.x.x

### ISSUE THREAD

**Issue by hektorKS** [lukas-krecan/ShedLock#852]
**Describe the bug**
1. Which version do you use
```
+--- redis.clients:jedis:4.0.1
|    +--- org.slf4j:slf4j-api:1.7.32
|    +--- org.apache.commons:commons-pool2:2.11.1
|    +--- org.json:json:20211205
|    \--- com.google.code.gson:gson:2.8.9
+--- net.javacrumbs.shedlock:shedlock-provider-redis-jedis:4.30.0
|    +--- net.javacrumbs.shedlock:shedlock-core:4.30.0
|    |    \--- org.slf4j:slf4j-api:1.7.32
|    +--- redis.clients:jedis:3.7.0 -> 4.0.1 (*)
|    \--- org.slf4j:slf4j-api:1.7.32
```
2. Which Lock Provider
```net.javacrumbs.shedlock:shedlock-provider-redis-jedis```
3. ShedLock configuration
```---```
4. ShedLock logs
```
contentType2022-01-11T14:17:22.174990152+01:00 2022-01-11 13:17:22.174 ERROR 1 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
contentType2022-01-11T14:17:22.175016696+01:00
contentType2022-01-11T14:17:22.175021122+01:00 java.lang.NoSuchMethodError: 'java.lang.Long redis.clients.jedis.Jedis.del(java.lang.String)'
contentType2022-01-11T14:17:22.175024096+01:00 	at net.javacrumbs.shedlock.provider.redis.jedis.JedisLockProvider$JedisPoolTemplate.del(JedisLockProvider.java:163)
contentType2022-01-11T14:17:22.175028180+01:00 	at net.javacrumbs.shedlock.provider.redis.jedis.JedisLockProvider$RedisLock.doUnlock(JedisLockProvider.java:115)
contentType2022-01-11T14:17:22.175032400+01:00 	at net.javacrumbs.shedlock.core.AbstractSimpleLock.unlock(AbstractSimpleLock.java:35)
contentType2022-01-11T14:17:22.175036256+01:00 	at net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor.executeWithLock(DefaultLockingTaskExecutor.java:79)
contentType2022-01-11T14:17:22.175040323+01:00 	at net.javacrumbs.shedlock.spring.aop.MethodProxyScheduledLockAdvisor$LockingInterceptor.invoke(MethodProxyScheduledLockAdvisor.java:86)
contentType2022-01-11T14:17:22.175043049+01:00 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
contentType2022-01-11T14:17:22.175045440+01:00 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
contentType2022-01-11T14:17:22.175047877+01:00 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
contentType2022-01-11T14:17:22.175050296+01:00 	at XXXHIDDENXXX$$EnhancerBySpringCGLIB$$f9a750ec.run(<generated>)
contentType2022-01-11T14:17:22.175052938+01:00 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
contentType2022-01-11T14:17:22.175055288+01:00 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
contentType2022-01-11T14:17:22.175057626+01:00 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
contentType2022-01-11T14:17:22.175060029+01:00 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
contentType2022-01-11T14:17:22.175062411+01:00 	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
contentType2022-01-11T14:17:22.175074600+01:00 	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
contentType2022-01-11T14:17:22.175077176+01:00 	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
contentType2022-01-11T14:17:22.175079805+01:00 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
contentType2022-01-11T14:17:22.175082833+01:00 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
contentType2022-01-11T14:17:22.175085191+01:00 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
contentType2022-01-11T14:17:22.175087633+01:00 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
contentType2022-01-11T14:17:22.175089970+01:00 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
contentType2022-01-11T14:17:22.175092431+01:00 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Expected behavior**
Be able to use jedis 4.X.X.

**Actual behavior**
Please, update jedis to the latest version.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. This is unfortunate, apparently Jedis changed del method from 
```
 public Long del(String key)
```
to

```
public long del(final String key)
```
so compile code does not work. Will try to figure out how to fix that

**Comment by hektorKS** [comment]
Ye, unfortunate even more because upgrading Jedis version to 4.x.x would break compatibility for people using Jedis before 4.x.x

**Comment by lukas-krecan** [comment]
4.31.0 contains new module `shedlock-provider-redis-jedis4` that supports Jedis 4
