### ISSUE TITLE
ShedLock failed to recover

### ISSUE THREAD

**Issue by mivanov1988** [lukas-krecan/ShedLock#898]
**Describe the bug**
1. Which version do you use - **shedlock-spring:4.25.0**
2. Which Lock Provider - **shedlock-provider-jdbc-template:4.25.0** 

Hello, we have been using the ShedLock for 5 months without any issues. However, last week we encountered a database (CockroachDB) outage that took about 6 minutes. After the database was restored the ShedLock failed to recover. It just stopped trying to retry the query.

Do you have any idea what may have prevented the ShedLock from being restored?

Exception during the outage:
```
com.service.locks.CustomLockProvider Releasing lock watchJobs_schedulerLock
Jan 28 05:48:56  	org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [UPDATE shedlock SET lock_until = ? WHERE name = ?]; SQL state [XXUUU]; error code [0]; ERROR: remote wall time is too far ahead (582.23817ms) to be trustworthy; nested exception is org.postgresql.util.PSQLException: ERROR: remote wall time is too far ahead (582.23817ms) to be trustworthy
Jan 28 05:48:56 	Caused by: org.postgresql.util.PSQLException: ERROR: remote wall time is too far ahead (582.23817ms) to be trustworthy
...
Jan 28 05:50:52	Caused by: org.postgresql.util.PSQLException: ERROR: remote wall time is too far ahead (664.529504ms) to be trustworthy
```

Full log:
```
Jan 28 05:50:46  [thread-1] org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler Unexpected error occurred in scheduled task
Jan 28 05:50:46  org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [UPDATE shedlock SET lock_until = ?, locked_at = ?, locked_by = ? WHERE name = ? AND lock_until <= ?]; SQL state [XXUUU]; error code [0]; ERROR: remote wall time is too far ahead (663.496474ms) to be trustworthy; nested exception is org.postgresql.util.PSQLException: ERROR: remote wall time is too far ahead (663.496474ms) to be trustworthy
org.springframework.jdbc.UncategorizedSQLException
Jan 28 05:50:46  at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1542)
Jan 28 05:50:46  at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:667)
Jan 28 05:50:46  at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:960)
Jan 28 05:50:46  at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:981)
Jan 28 05:50:46  at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.update(NamedParameterJdbcTemplate.java:328)
Jan 28 05:50:46  at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.update(NamedParameterJdbcTemplate.java:333)
Jan 28 05:50:46  at net.javacrumbs.shedlock.provider.jdbctemplate.JdbcTemplateStorageAccessor.lambda$execute$0(JdbcTemplateStorageAccessor.java:111)
Jan 28 05:50:46  at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
Jan 28 05:50:46  at net.javacrumbs.shedlock.provider.jdbctemplate.JdbcTemplateStorageAccessor.execute(JdbcTemplateStorageAccessor.java:111)
Jan 28 05:50:46  at net.javacrumbs.shedlock.provider.jdbctemplate.JdbcTemplateStorageAccessor.updateRecord(JdbcTemplateStorageAccessor.java:77)
Jan 28 05:50:46  at net.javacrumbs.shedlock.support.StorageBasedLockProvider.doLock(StorageBasedLockProvider.java:91)
Jan 28 05:50:46  at net.javacrumbs.shedlock.support.StorageBasedLockProvider.lock(StorageBasedLockProvider.java:65)
Jan 28 05:50:46  at com.my.package.service.locks.CustomLockProvider.lock(CustomLockProvider.java:34)
Jan 28 05:50:46  at jdk.internal.reflect.GeneratedMethodAccessor86.invoke(Unknown Source)
Jan 28 05:50:46  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
Jan 28 05:50:46  at java.base/java.lang.reflect.Method.invoke(Unknown Source)
Jan 28 05:50:46  at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
Jan 28 05:50:46  at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
Jan 28 05:50:46  at com.sun.proxy.$Proxy115.lock(Unknown Source)
Jan 28 05:50:46  at net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor.executeWithLock(DefaultLockingTaskExecutor.java:63)
Jan 28 05:50:46  at net.javacrumbs.shedlock.spring.aop.MethodProxyScheduledLockAdvisor$LockingInterceptor.invoke(MethodProxyScheduledLockAdvisor.java:86)
Jan 28 05:50:46  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Jan 28 05:50:46  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
Jan 28 05:50:46  at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
Jan 28 05:50:46  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Jan 28 05:50:46  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
Jan 28 05:50:46  at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
Jan 28 05:50:46  at com.my.package.service.monitoring.DataJobMonitor$$EnhancerBySpringCGLIB$$46c5c2fc.watchJobs(<generated>)
Jan 28 05:50:46  at jdk.internal.reflect.GeneratedMethodAccessor84.invoke(Unknown Source)
Jan 28 05:50:46  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
Jan 28 05:50:46  at java.base/java.lang.reflect.Method.invoke(Unknown Source)
Jan 28 05:50:46  at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
Jan 28 05:50:46  at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
Jan 28 05:50:46  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
Jan 28 05:50:46  at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
Jan 28 05:50:46  at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
Jan 28 05:50:46  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
Jan 28 05:50:46  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
Jan 28 05:50:46  at java.base/java.lang.Thread.run(Unknown Source)
Jan 28 05:50:46  Caused by: org.postgresql.util.PSQLException: ERROR: remote wall time is too far ahead (663.496474ms) to be trustworthy
Jan 28 05:50:46  at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2552)
Jan 28 05:50:46  at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2284)
Jan 28 05:50:46  at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322)
Jan 28 05:50:46  at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
Jan 28 05:50:46  at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
Jan 28 05:50:46  at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
Jan 28 05:50:46  at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:130)
Jan 28 05:50:46  at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
Jan 28 05:50:46  at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
Jan 28 05:50:46  at org.springframework.jdbc.core.JdbcTemplate.lambda$update$2(JdbcTemplate.java:965)
Jan 28 05:50:46  at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:651)
Jan 28 05:50:46  at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:960)
Jan 28 05:50:46  at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:981)
Jan 28 05:50:46  at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.update(NamedParameterJdbcTemplate.java:328)
Jan 28 05:50:46  at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.update(NamedParameterJdbcTemplate.java:333)
Jan 28 05:50:46  at net.javacrumbs.shedlock.provider.jdbctemplate.JdbcTemplateStorageAccessor.lambda$execute$0(JdbcTemplateStorageAccessor.java:111)
Jan 28 05:50:46  at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
Jan 28 05:50:46  at net.javacrumbs.shedlock.provider.jdbctemplate.JdbcTemplateStorageAccessor.execute(JdbcTemplateStorageAccessor.java:111)
Jan 28 05:50:46  at net.javacrumbs.shedlock.provider.jdbctemplate.JdbcTemplateStorageAccessor.updateRecord(JdbcTemplateStorageAccessor.java:77)
Jan 28 05:50:46  at net.javacrumbs.shedlock.support.StorageBasedLockProvider.doLock(StorageBasedLockProvider.java:91)
Jan 28 05:50:46  at net.javacrumbs.shedlock.support.StorageBasedLockProvider.lock(StorageBasedLockProvider.java:65)
Jan 28 05:50:46  at com.my.package.service.locks.CustomLockProvider.lock(CustomLockProvider.java:34)
Jan 28 05:50:46  at jdk.internal.reflect.GeneratedMethodAccessor86.invoke(Unknown Source)
Jan 28 05:50:46  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
Jan 28 05:50:46  at java.base/java.lang.reflect.Method.invoke(Unknown Source)
Jan 28 05:50:46  at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
Jan 28 05:50:46  at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
Jan 28 05:50:46  at com.sun.proxy.$Proxy115.lock(Unknown Source)
Jan 28 05:50:46  at net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor.executeWithLock(DefaultLockingTaskExecutor.java:63)
Jan 28 05:50:46  at net.javacrumbs.shedlock.spring.aop.MethodProxyScheduledLockAdvisor$LockingInterceptor.invoke(MethodProxyScheduledLockAdvisor.java:86)
Jan 28 05:50:46  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Jan 28 05:50:46  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
Jan 28 05:50:46  at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
Jan 28 05:50:46  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Jan 28 05:50:46  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
Jan 28 05:50:46  at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
Jan 28 05:50:46  at com.my.package.service.monitoring.DataJobMonitor$$EnhancerBySpringCGLIB$$46c5c2fc.watchJobs(<generated>)
Jan 28 05:50:46  at jdk.internal.reflect.GeneratedMethodAccessor84.invoke(Unknown Source)
Jan 28 05:50:46  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
Jan 28 05:50:46  at java.base/java.lang.reflect.Method.invoke(Unknown Source)
Jan 28 05:50:46  at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
Jan 28 05:50:46  at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
Jan 28 05:50:46  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
Jan 28 05:50:46  at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
Jan 28 05:50:46  at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
Jan 28 05:50:46  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
Jan 28 05:50:46  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
Jan 28 05:50:46  at java.base/java.lang.Thread.run(Unknown Source)
Jan 28 05:50:47  [thread-1] org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler Unexpected error occurred in scheduled task
Jan 28 05:50:47  org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [UPDATE shedlock SET lock_until = ?, locked_at = ?, locked_by = ? WHERE name = ? AND lock_until <= ?]; SQL state [XXUUU]; error code [0]; ERROR: remote wall time is too far ahead (663.071882ms) to be trustworthy; nested exception is org.postgresql.util.PSQLException: ERROR: remote wall time is too far ahead (663.071882ms) to be trustworthy
org.springframework.jdbc.UncategorizedSQLException
Jan 28 05:50:47  at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1542)
Jan 28 05:50:47  at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:667)
Jan 28 05:50:47  at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:960)
Jan 28 05:50:47  at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:981)
Jan 28 05:50:47  at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.update(NamedParameterJdbcTemplate.java:328)
Jan 28 05:50:47  at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.update(NamedParameterJdbcTemplate.java:333)
Jan 28 05:50:47  at net.javacrumbs.shedlock.provider.jdbctemplate.JdbcTemplateStorageAccessor.lambda$execute$0(JdbcTemplateStorageAccessor.java:111)
Jan 28 05:50:47  at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
```

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. What is the content of the full log? It does not seem to be one stack trace.

**Comment by mivanov1988** [comment]
> I will not be able to help you much as I am not an expert in CocroachDB. [This looks](https://github.com/cockroachdb/cockroach/issues/42570#issuecomment-559087646) similar though.

CockroachDB uses the Postgresql driver and syntax. So it shouldn't be the problem.

**Comment by mivanov1988** [comment]
> Hi, thanks for feedback. What is the content of the full log? It does not seem to be one stack trace.

I have just updated the log.

**Comment by mivanov1988** [comment]
The question is why the ShedLock stopped trying to recover. Is it possible that it is because of `org.springframework.jdbc.UncategorizedSQLException`?

**Comment by lukas-krecan** [comment]
What do you mean try to recover? What would you expect it to do?

According to the log, ShedLock is trying to obtain a lock but it gets an unexpected exception. It can't proceed since it can't obtain the lock, so it rethrows the exception. On the next execution it will try to obtain the lock again, if the error disappears, it will start working, if the clockskew (or what's the reason) persists, it will keep failing.

**Comment by mivanov1988** [comment]
Yes, but when the error disappeared it didn't start.

**Comment by lukas-krecan** [comment]
What did not start? ShedLock is just a lock, there is nothing to start. What might have happened is that the unlock failed as well and now the lock is waihing for the the fallback `lockAtMostFor` interval to pass.

**Comment by mivanov1988** [comment]
Ok, thanks.

**Comment by lukas-krecan** [comment]
If you want to fix it manually, feel free to change the lock_util column value manually.
